### ISSUE TITLE
emotion/babel fails on styled-jsx element

### ISSUE THREAD

**Issue by mattfysh** [tkh44/emotion#145]
- `emotion` version: 5.2.0
- `react` version: 15.6.1

Relevant code.

```javascript
<style jsx>
  {nprogressStyle}
</style>
```

What you did:

Tried to compile a file containing the javascript snippet above (fyi, attempting to slowly migrate from styled-jsx to emotion)

What happened:

```
Module build failed: SyntaxError: /web/src/page/Header/index.js: undefined is not a string or template literal (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (/web/node_modules/babel-core/lib/transformation/file/index.js:427:15)
    at NodePath.buildCodeFrameError (/web/node_modules/babel-traverse/lib/path/index.js:140:26)
    at exports.default (/web/node_modules/emotion/lib/css-prop.js:44:16)
    at PluginPass.JSXOpeningElement (/web/node_modules/emotion/lib/babel.js:42:31)
    at newFn (/web/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/web/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/web/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/web/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/web/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/web/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/web/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/web/node_modules/babel-traverse/lib/index.js:114:17)
 @ ./pages?entry 3:14-43
```

Reproduction:

NA

Problem description:

NA

Suggested solution:

NA

**Comment by mattfysh** [comment]
Ignore this - it's a conflict between `styled-jsx` and `emotion`. styled-jsx runs first and adds a css attribute to `<style jsx>`, which is then parsed by emotion. I was hoping to transition slowly but I'll have to go the whole hog and migrate completely

**Comment by tkh44** [comment]
It's really interesting that it almost works 😅
