### ISSUE TITLE
Can't test components that use "emotion/react" using jest

### ISSUE THREAD

**Issue by carrickjason** [tkh44/emotion#170]
When I try to run Jest tests on components that import anything from "emotion/react", I get a SyntaxError. 

```javascript
● Test suite failed to run

    /Users/jcarrick/Sites/pp-application/node_modules/emotion/src/react.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Component, createElement as h } from 'react'
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (node_modules/emotion/lib/react.js:87:14)
      at Object.<anonymous> (src/components/Checkbox.js:4:15)
```

I have followed [Jest's suggested .babelrc set up to transform es6 modules to commonJs](https://facebook.github.io/jest/docs/webpack.html#using-with-webpack-2) but it is obviously having no effect on "emotion/src/react.js"

Here is my .babelrc file for reference:
```javascript
{
  "presets": [
    ["es2015", { "modules": false }],
    "react",
    "stage-0"
  ],
  "plugins": [
    "react-hot-loader/babel",
    "syntax-dynamic-import",
    ["emotion/babel", { "inline": true }]
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs",
        "dynamic-import-node"
      ]
    }
  }
}
```

- `emotion` version: 5.2.1
- `react` version: 15.6.1
- `jest` version: 20.0.4

**Comment by mitchellhamilton** [comment]
It looks like the `src` folder is being imported instead of the `lib` folder. Could you try on the latest version of `emotion`?

**Comment by carrickjason** [comment]
@mitchellhamilton I updated to version 6.0.3 but am receiving the same result.

**Comment by tkh44** [comment]
Try putting emotion first in the plugin list.

```jsx
{
  "presets": [
    ["es2015", { "modules": false }],
    "react",
    "stage-0"
  ],
  "plugins": [
     ["emotion/babel", { "inline": true }],    
    "react-hot-loader/babel",
    "syntax-dynamic-import",
  ],
  "env": {
    "test": {
      "plugins": [
         ["emotion/babel", { "inline": true }], // <- this may need to be done as well
        "transform-es2015-modules-commonjs",
        "dynamic-import-node"
      ]
    }
  }
}
```

**Comment by carrickjason** [comment]
So it looks like there must have been some sort of naming conflict.  My root directory was `./src`, I changed that to `./app` and it worked with my original `.babelrc` setup.  I don't understand why yet, but that must have been making it look for `emotion/react` in `emotion/src/react.js`

This was my `webpack.config.js`

```javascript
const webpack = require('webpack')
const path = require('path')

module.exports = {
  devtool: 'eval',
  entry: {
    client: [
      'babel-polyfill',
      'react-hot-loader/patch',
      './src/client'
    ],
    vendor: [
      'react',
      'react-dom'
    ]
  },
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    publicPath: '/'
  },
  module: {
    loaders: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'eslint-loader'
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest']
    }),
    new webpack.optimize.ModuleConcatenationPlugin()
  ],
  resolve: {
    extensions: ['.js', '.jsx', '.json'],
    modules: [
      path.resolve('./src'),
      'node_modules'
    ]
  }
}
```

Any Ideas why that would be an issue? 

Anyways, Thank you @mitchellhamilton and @tkh44

**Comment by tkh44** [comment]
It very well could have been a babel caching issue with jest. Sometimes you have to run jest with `--no-cache` flag or `--resetModules` to get it unstuck.

**Comment by thangngoc89** [comment]
Oh. I just have this issue. It maybe caused by https://openit.io/babel-plugin-jsx-pragmatic 
I append `import React` statement if React not available in the scope. And somehow it messes up with Jest transpile. If you're having this problem, try adding `import React from "react"` on top of your test file

**Comment by Geczy** [comment]
Have this issue as well, but haven't been able to fix it. 

Tried `["emotion/babel", { "inline": true }],` under `test` without success

Error
```
  ● Test suite failed to run

    C:\Users\Matt\Documents\GitHub\frontend\node_modules\emotion\src\react\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Component, createElement as h } from 'react'
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (node_modules/emotion/lib/react/index.js:132:14)
      at Object.<anonymous> (node_modules/emotion/react/index.js:1:107)
```


.babelrc
```json
{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ],
    "react",
    "stage-1"
  ],
  "plugins": [
    "emotion/babel",
    "react-hot-loader/babel"
  ],
  "env": {
    "development": {
      "plugins": [
        "emotion/babel",
        "transform-es2015-modules-commonjs",
        "transform-async-to-generator"
      ]
    },
    "test": {
      "plugins": [
        "emotion/babel",
        "transform-es2015-modules-commonjs"
      ]
    },
    "production": {
      "plugins": [
        "transform-react-remove-prop-types"
      ]
    }
  }
}
```

**Comment by Geczy** [comment]
@mitchellhamilton ^ seems similar to my previous issue

**Comment by Geczy** [comment]
Funny, I changed my `src` dir to `app` too and that fixes this issue. Still would be good to open this and figure out the real problem

**Comment by tkh44** [comment]
The only thing in your webpack config that mentions src is this ```path.resolve('./src')```. I wonder if that is somehow messing with it. Unless you changed that when you changed from `src` to `app`.

**Comment by Geczy** [comment]
I had:

```js
  const sourceDir = process.env.SOURCE || 'src'
  resolve({ modules: [path.resolve(sourceDir), 'node_modules'] }),
```

I changed my env SOURCE to `app` to fix the issue

**Comment by Geczy** [comment]
I also did have  `NODE_PATH=src` in my `.env`, which I changed to `app` too. So I'm not sure if it was this

**Comment by Geczy** [comment]
Removed node_path=src, changed back folder to src, but still fails

So it wasn't that

**Comment by thangngoc89** [comment]
@Geczy You are not transpiling import statement 

```
 "presets": [
    [
      "env",
      {
        "modules": false
      }
    ],
```
