### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Geczy** [tkh44/emotion#186]
- `emotion` version: 6.0.3
- `react` version: 15.6.1

Relevant code.

```javascript
import { injectGlobal } from 'emotion'
```

```javascript
require('dotenv').config({ silent: true })

const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const InterpolateHtmlPlugin = require('interpolate-html-plugin')
const devServer = require('@webpack-blocks/dev-server2')
const splitVendor = require('webpack-blocks-split-vendor')
const happypack = require('webpack-blocks-happypack')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const {
  addPlugins, createConfig, entryPoint, env, setOutput,
  sourceMaps, defineConstants, webpack,
} = require('@webpack-blocks/webpack2')

const host = process.env.HOST || 'localhost'
const port = process.env.PORT || 3000
const sourceDir = process.env.SOURCE || 'src'
const publicPath = `/${process.env.PUBLIC_PATH || ''}/`.replace('//', '/')
const sourcePath = path.join(process.cwd(), sourceDir)
const outputPath = path.join(process.cwd(), 'dist')

// Get environment variables to inject into our app.
const getClientEnvironment = require('./scripts/env')

const appEnv = getClientEnvironment(publicPath)
const PROD = process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'test'

const babel = () => () => ({
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
    ],
  },
})

const assets = () => () => ({
  module: {
    rules: [
      { test: /\.(png|jpe?g|svg|woff2?|ttf|eot)$/, loader: 'url-loader?limit=8000' },
      {
        test: /\.css$/,
        exclude: /emotion\.css$/,
        use: PROD
          ? ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: {
              loader: 'css-loader',
              options: {
                sourceMap: true,
                modules: true,
              },
            },
          })
          : ['style-loader', { loader: 'css-loader', options: { modules: true } }],
      },
      {
        test: /emotion\.css$/,
        use: PROD
          ? ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: {
              loader: 'css-loader',
              options: {
                sourceMap: true,
              },
            },
          })
          : ['style-loader', { loader: 'css-loader' }],
      },
      {
        test: /\.(jpg|png|svg)$/,
        loader: 'url-loader',
        options: {
          limit: 25000,
        },
      },
      {
        loader: 'raw-loader',
        test: /\.(example|md)$/,
      },
    ],
  },
})

const resolveModules = modules => () => ({
  resolve: {
    modules: [].concat(modules, ['node_modules']),
  },
})

const config = createConfig([
  entryPoint({
    app: sourcePath,
  }),
  setOutput({
    filename: '[name].js',
    path: outputPath,
    publicPath,
  }),
  defineConstants({
    'process.env.NODE_ENV': process.env.NODE_ENV,
    'process.env.PUBLIC_PATH': publicPath.replace(/\/$/, ''),
  }),
  addPlugins([
    new webpack.ProgressPlugin(),
    new webpack.DefinePlugin(appEnv.stringified),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: path.join(process.cwd(), 'public/index.html'),
    }),
    new InterpolateHtmlPlugin(appEnv.raw),
  ]),
  assets(),
  happypack([
    babel(),
  ]),
  resolveModules(sourceDir),

  env('development', [
    devServer({
      contentBase: 'public',
      stats: 'errors-only',
      historyApiFallback: { index: publicPath },
      headers: { 'Access-Control-Allow-Origin': '*' },
      host,
      port,
    }),
    sourceMaps(),
    addPlugins([
      new webpack.NamedModulesPlugin(),
    ]),
  ]),
  env('test', [
    splitVendor(),
    addPlugins([
      new webpack.optimize.UglifyJsPlugin({ compress: { warnings: false } }),
      new ExtractTextPlugin('styles.css'),
    ]),
  ]),
  env('production', [
    splitVendor(),
    addPlugins([
      new webpack.optimize.UglifyJsPlugin({ compress: { warnings: false } }),
      new ExtractTextPlugin('styles.css'),
    ]),
  ]),
])

module.exports = config

```

```javascript
{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ],
    "react",
    "stage-1"
  ],
  "plugins": [
    "emotion/babel",
    "react-hot-loader/babel"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-es2015-modules-commonjs",
        "transform-async-to-generator"
      ]
    },
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs"
      ]
    },
    "production": {
      "plugins": [
        "transform-react-remove-prop-types"
      ]
    }
  }
}

```

What you did:
Refreshed my page

What happened:

```javascript
Uncaught ReferenceError: exports is not defined
    at Object../src/components/App.js (App.emotion.css?589c:26)
    at __webpack_require__ (bootstrap 79b3ad5…:659)
    at fn (bootstrap 79b3ad5…:85)
    at Object../src/index.js (index.js:12)
    at __webpack_require__ (bootstrap 79b3ad5…:659)
    at fn (bootstrap 79b3ad5…:85)
    at Object.0 (selectors.js:4)
    at __webpack_require__ (bootstrap 79b3ad5…:659)
    at ./node_modules/airbnb-prop-types/build/and.js.Object.defineProperty.value (bootstrap 79b3ad5…:708)
    at app.js:712
```

**Comment by tkh44** [comment]
Try putting "emotion/babel" as the first plugin in both "development" and "test"

**Comment by Geczy** [comment]
Now new error:

```javascript
ERROR in ./src/components/App.js                
Module build failed: SyntaxError: C:/Users/Matt/Documents/GitHub/frontend/src/components/App.js: NodePath has been removed so is read-only. (This is an error on an internal node. Probably an internal error)
```

**Comment by Geczy** [comment]
I did upgrade to Webpack 3 so maybe that is causing it? 

```javascript
require('dotenv').config({ silent: true })

const webpack = require('webpack')
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const InterpolateHtmlPlugin = require('interpolate-html-plugin')
const devServer = require('@webpack-blocks/dev-server')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const {
  addPlugins, createConfig, entryPoint, env, setOutput, customConfig,
  sourceMaps, defineConstants, resolve,
} = require('@webpack-blocks/webpack')

const babel = require('@webpack-blocks/babel6')

const host = process.env.HOST || 'localhost'
const port = process.env.PORT || 3000
const sourceDir = process.env.SOURCE || 'src'
const publicPath = `/${process.env.PUBLIC_PATH || ''}/`.replace('//', '/')
const sourcePath = path.join(process.cwd(), sourceDir)
const outputPath = path.join(process.cwd(), 'dist')

// Get environment variables to inject into our app.
const getClientEnvironment = require('./scripts/env')

const appEnv = getClientEnvironment(publicPath)


const config = createConfig([
  entryPoint({
    app: sourcePath,
  }),
  setOutput({
    filename: '[name].js',
    path: outputPath,
    publicPath,
  }),
  defineConstants({
    'process.env.NODE_ENV': process.env.NODE_ENV,
    'process.env.PUBLIC_PATH': publicPath.replace(/\/$/, ''),
  }),
  addPlugins([
    new webpack.ProgressPlugin(),
    new webpack.DefinePlugin(appEnv.stringified),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: path.join(process.cwd(), 'public/index.html'),
    }),
    new InterpolateHtmlPlugin(appEnv.raw),
  ]),
  babel(),
  resolve({ modules: [].concat(sourceDir, ['node_modules']) }),
  env('development', [
    devServer({
      contentBase: 'public',
      stats: 'errors-only',
      historyApiFallback: { index: publicPath },
      headers: { 'Access-Control-Allow-Origin': '*' },
      host,
      port,
    }),
    sourceMaps(),
    addPlugins([
      new webpack.NamedModulesPlugin(),
    ]),
  ]),
  env('test', [
    addPlugins([
      new webpack.optimize.ModuleConcatenationPlugin(),
      new webpack.optimize.UglifyJsPlugin({
        beautify: false,
        output: {
          comments: false,
        },
        mangle: {
          screw_ie8: true,
        },
        compress: {
          screw_ie8: true,
          warnings: false,
          conditionals: true,
          unused: true,
          comparisons: true,
          sequences: true,
          dead_code: true,
          evaluate: true,
          if_return: true,
          join_vars: true,
          negate_iife: false,
        },
        sourceMap: false,
      }),
    ]),
  ]),
  env('production', [
    addPlugins([
      new webpack.optimize.ModuleConcatenationPlugin(),
      new webpack.optimize.UglifyJsPlugin({
        beautify: false,
        output: {
          comments: false,
        },
        mangle: {
          screw_ie8: true,
        },
        compress: {
          screw_ie8: true,
          warnings: false,
          conditionals: true,
          unused: true,
          comparisons: true,
          sequences: true,
          dead_code: true,
          evaluate: true,
          if_return: true,
          join_vars: true,
          negate_iife: false,
        },
        sourceMap: false,
      }),
    ]),
  ]),
])

module.exports = config
```

```javascript
{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ],
    "react",
    "stage-1"
  ],
  "plugins": [
    "emotion/babel",
    "react-hot-loader/babel"
  ],
  "env": {
    "development": {
      "plugins": [
        "emotion/babel",
        "transform-es2015-modules-commonjs",
        "transform-async-to-generator",
        [
          "styled-components",
          {
            "minify": false
          }
        ]
      ]
    },
    "test": {
      "plugins": [
        "emotion/babel",
        "transform-es2015-modules-commonjs"
      ]
    },
    "production": {
      "plugins": [
        "transform-react-remove-prop-types",
        [
          "styled-components",
          {
            "displayName": false
          }
        ]
      ]
    }
  }
}
```

**Comment by tkh44** [comment]
Any ideas @mitchellhamilton ?

**Comment by mitchellhamilton** [comment]
@Geczy could you try removing the `styled-components` babel plugin?

**Comment by Geczy** [comment]
Same issue, here's more of a stack trace

```javascript
ERROR in ./src/components/App.js                
Module build failed: SyntaxError: C:/Users/Matt/Documents/GitHub/frontend/src/components/App.js: NodePath has been removed so is read-only. (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-core\lib\transformation\file\index.js:427:15)
    at NodePath.buildCodeFrameError (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\path\index.js:140:26)
    at NodePath._assertUnremoved (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\path\removal.js:70:16)
    at NodePath.remove (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\path\removal.js:20:8)
    at replaceGlobalWithCallExpression (C:\Users\Matt\Documents\GitHub\frontend\node_modules\emotion\lib\babel.js:264:23)
    at PluginPass.TaggedTemplateExpression (C:\Users\Matt\Documents\GitHub\frontend\node_modules\emotion\lib\babel.js:91:13)
    at newFn (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (C:\Users\Matt\Documents\GitHub\frontend\node_modules\babel-traverse\lib\context.js:150:16)
 @ ./src/index.js 31:11-36 56:2-59:4 57:4-29
```

**Comment by mitchellhamilton** [comment]
Could you share the contents of `./src/components/App.js`? Also am I correct in assuming that this error is happening in `development`?

**Comment by Geczy** [comment]
Sure, and yes this is happening in `development` on my Windows machine with npm v5.3.0 and node v8.2.1

https://gist.github.com/Geczy/7a322fef8d51ad06908c9b4f8357c062

**Comment by mitchellhamilton** [comment]
This is going to sound weird but could you try assigning what is returned from `injectGlobal` to a variable.
```jsx
const something = injectGlobal`

`

**Comment by Geczy** [comment]
That did work! Now back to the loader issue:

```javascript
ERROR in ./src/components/App.emotion.css        
Module parse failed: C:\Users\Matt\Documents\GitHub\frontend\src\components\App.emotion.css Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
| body {
|     font-family: 'Open Sans', sans-serif;
|     line-height: 24px;
 @ ./src/components/App.js 7:0-28
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?https://app-local.unific.com:443 webpack/hot/only-dev-server ./src
```

**Comment by mitchellhamilton** [comment]
For that you need to add a loader that handles css. I'm guessing you could use [this](https://github.com/andywer/webpack-blocks/tree/master/packages/extract-text) but I'm not too familiar with `webpack-blocks`

**Comment by mitchellhamilton** [comment]
Could you share what is returned from console.log ing `config.module`?

**Comment by mitchellhamilton** [comment]
Actually, could you change where `loaders` to `rules` in the `module` object?

**Comment by Geczy** [comment]
Changed, it compiled successfully ! 👍 

Now loading the localhost, receive this in console log:

```javascript
Uncaught TypeError: (0 , _emotion2.default) is not a function
    at Object../src/components/atoms/LeftNavLink/index.js (app.js:195202)
    at __webpack_require__ (app.js:670)
    at fn (app.js:88)
    at webpackContext (app.js:194720)
    at app.js:195786
    at Array.forEach (<anonymous>)
    at Object../src/components/index.js (app.js:195784)
    at __webpack_require__ (app.js:670)
    at fn (app.js:88)
    at Object../src/components/App.js (app.js:194784)
```

**Comment by mitchellhamilton** [comment]
You're probably importing `styled` from `emotion` instead of `emotion/react`

**Comment by Geczy** [comment]
```js
import styled, { css } from 'emotion'
```

You're right. I can try /react, last time it had babel issues

**Comment by Geczy** [comment]
```js
./node_modules/emotion/src/react/index.js
Module parse failed: C:\Users\Matt\Documents\GitHub\frontend\node_modules\emotion\src\react\index.js Unexpected token (17:10)
You may need an appropriate loader to handle this file type.
| 
|   class Styled extends Component {
|     state = {
|       theme: {}
|     }
 @ ./node_modules/emotion/lib/react/index.js 132:13-29
 @ ./node_modules/emotion/react/index.js
 @ ./src/components/atoms/LeftNavLink/index.js
 @ ./src/components \.\/[^\/]+\/[^\/]+\/index\.js$
 @ ./src/components/index.js
 @ ./src/components/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?https://app.com:443 webpack/hot/only-dev-server ./src
```

**Comment by mitchellhamilton** [comment]
This is very strange, it seems like `emotion/src/react/index.js` is being imported from `emotion/lib/react/index.js`

**Comment by mitchellhamilton** [comment]
Could you change `sourceDir` to a `path.resolve(whereEverItIs)`?

**Comment by mitchellhamilton** [comment]
I think webpack is importing `emotion/src/react/index.js` instead of importing `react`(the line it mentions is the line that `react` is imported on) because of the module resolve stuff.

**Comment by Geczy** [comment]
Changed to `resolve({ modules: ["src", "node_modules"]}),`

Same issue 

```js
ERROR in ./node_modules/emotion/src/react/index.js
Module parse failed: C:\Users\Matt\Documents\GitHub\frontend\node_modules\emotion\src\react\index.js Unexpected token (17:10)
You may need an appropriate loader to handle this file type.
| 
|   class Styled extends Component {
|     state = {
|       theme: {}
|     }
 @ ./node_modules/emotion/lib/react/index.js 132:13-29
 @ ./node_modules/emotion/react/index.js
 @ ./src/components/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?https://app-local.unific.com:443 webpack/hot/only-dev-server ./src
```

**Comment by Geczy** [comment]
Would it help if I emailed you a copy of the project?

**Comment by mitchellhamilton** [comment]
```jsx
const path = require('path')
resolve({ modules: [path.resolve('src'), "node_modules"]})
```

**Comment by mitchellhamilton** [comment]
I think I already have a repro of this in another project.

**Comment by Geczy** [comment]
Tried that as well according to docs but it caused unrelated errors
https://webpack.js.org/configuration/resolve/#resolve-modules

Removing `__dirname` works, however

And...It all compiled! 🎉 🎈 
No issues in console

**Comment by Geczy** [comment]
Yes

**Comment by DominicTobias-b1** [comment]
I've run into this issue too upgrading to Emotion 11, looks like someone else did too - https://stackoverflow.com/questions/54272194/emotion-css-in-js-referenceerror-exports-is-not-defined

Consuming a component library results in this, I've tried compiling with typescript and with babel:

```js
const globals = {
  react: 'React',
  'react-dom': 'ReactDOM',
}
const external = Object.keys(globals)
const extensions = ['.ts', '.tsx']
const env = process.env.NODE_ENV
const isProd = env === 'production'

export default {
  input: 'src/index.ts',
  output: {
    file: 'dist/index.js',
    format: 'esm',
    globals,
  },
  plugins: [
    isProd &&
      cleaner({
        targets: ['./dist/'],
      }),
    postcss({
      extensions: ['.css'],
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify(env),
    }),
    commonjs(),
    nodeResolve({
      preferBuiltins: true,
      extensions,
    }),
    // Just used for type checking.
    typescript({
      tsconfigOverride: {
        emitDeclarationOnly: true,
      },
    }),
    babel({ extensions, babelHelpers: 'bundled' }),
    json(),
  ],
  external,
}
```

.babelrc

```json
{
  "plugins": [
    "@emotion"
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "entry",
        "corejs": 3,
        // The babel setup in CRA Webpack throws if we don't transpile out some
        // modern stuff like optional chaining (?) and nullish coalescence (??).
        "targets": {
          "esmodules": true
        }
      }
    ],
    "@babel/preset-typescript",
    [
      "@babel/preset-react",
      {
        "runtime": "automatic",
        "importSource": "@emotion/react"
      }
    ]
  ]
}
```
tsconfig.json:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es6",
    "module": "esnext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "outDir": "dist",
    "lib": ["dom", "dom.iterable", "esnext"],
    "strict": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "resolveJsonModule": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "jsx": "react-jsx",
    "jsxImportSource": "@emotion/react"
  },
  "include": ["src"]
}
```

Will update if I find a solution
